site_name: Adapter Documentation

theme:
  name: material
  logo: assets/icon.png
  favicon: assets/favicon.ico
  features:
    - navigation.sections
    - navigation.expand

nav:
  - Home: index.md
  - Requests & Response : blitz_order_requests.md
  - Zerodha: zerodha.md

extra_css:
  - css/custom.css

extra_javascript:
  - js/logo-link.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.extra
  - attr_list
